name: marine-edna-humann3
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  # Python version
  - python=3.9
  
  # Core bioinformatics tools
  - humann=3.6
  - metaphlan=4.0
  - diamond=2.0.15
  - bowtie2=2.5
  - samtools=1.17
  - fastp=0.23
  
  # Scientific computing
  - numpy=1.24
  - pandas=1.5
  - scipy=1.10
  - scikit-learn=1.2
  - statsmodels=0.13
  
  # Visualization
  - matplotlib=3.7
  - seaborn=0.12
  - plotly=5.14
  - altair=5.0
  - bokeh=3.1
  
  # Bioinformatics libraries
  - biopython=1.81
  - pysam=0.21
  
  # Jupyter ecosystem
  - jupyter=1.0
  - jupyterlab=3.6
  - jupytext=1.14
  - notebook=6.5
  - ipywidgets=8.0
  
  # Data processing
  - h5py=3.8
  - pytables=3.8
  - zarr=2.14
  - dask=2023.5
  
  # Quality control tools
  - fastqc=0.12
  - multiqc=1.14
  
  # Sequence processing
  - cutadapt=4.4
  - bbmap=39.01
  
  # Development tools
  - pytest=7.3
  - pytest-cov=4.1
  - black=23.3
  - flake8=6.0
  - mypy=1.3
  
  # Documentation
  - sphinx=6.2
  - sphinx_rtd_theme=1.2
  
  # Utilities
  - click=8.1
  - tqdm=4.65
  - pyyaml=6.0
  - requests=2.31
  - beautifulsoup4=4.12
  
  # Performance
  - numba=0.57
  - cython=0.29
  
  # Pip dependencies
  - pip
  - pip:
    # Marine-specific packages (if any become available)
    # - marine-microbiome-toolkit
    
    # Additional visualization
    - seaborn-image==0.5.0
    
    # Workflow management
    - snakemake==7.32.3
    
    # Interactive visualizations
    - holoviews==1.16.2
    - hvplot==0.8.4
    - panel==1.2.0
    
    # Network analysis
    - networkx==3.1
    
    # Machine learning extras
    - xgboost==1.7.5
    - lightgbm==3.3.5
    
    # Time series analysis
    - stumpy==1.11.1
    
    # Rich terminal output
    - rich==13.4.2
    
    # Configuration management
    - python-dotenv==1.0.0
    
    # Data validation
    - pandera==0.15.1
    
# Environment variables
variables:
  HUMANN_DB_DIR: ${HOME}/marine_edna_databases
  MPLBACKEND: Agg  # For headless systems